### ISSUE TITLE
No CriwareKey for hca files is logged while opening Blue Archive app in Bilibili server

### ISSUE THREAD

**Issue by ljgit428** [lico-n/ZygiskUnityCriwareKeylogger#1]
@lico-n The story scenario voicelines for Blue Archive in Bilibili are stored as files of .acb and .awb extensions. After I extracted them, they are encoded .hca files, and I need to find the key code to extract the wav files. After using ZygiskUnityCriwareKeylogger in Nox, I can only see the app is initialized, but there is no key logged with command `adb logcat -s ZygiskUnityCriwareKeylogger`. Here is the screen shot for the log I have.
![Snipaste_2023-11-02_07-39-49](https://github.com/lico-n/ZygiskUnityCriwareKeylogger/assets/50344179/7f96ba30-1066-4eda-910b-0adbe4bc16b4)

 The Magisk version I use is Magisk Delta 25306. I cannot install Magius app of any other versions with Zygisk working on Nox. Any suggestions/recommendations? 
![Snipaste_2023-11-02_07-56-39](https://github.com/lico-n/ZygiskUnityCriwareKeylogger/assets/50344179/8d90e399-19c8-4faa-9924-16e3c9b782e0)

**Comment by lico-n** [comment]
It's only tested with 64-bit emulators. Which nox emulator are you using? If you are using the default one, then that is 32-bit android 7 which is pretty old. Try a more up to date one with 64-bit

**Comment by ljgit428** [comment]
@lico-n I try to use ldplayer9, so now I have the logs ready, but I cannot find the key. I really appreciate your timely reply.

![image](https://github.com/lico-n/ZygiskUnityCriwareKeylogger/assets/50344179/70661a6b-b11f-49b0-a702-91913a76aef4)

I am sure that CriWareDrypterConfig initialized by CriWareDrypter class function has the field key.
![Snipaste_2023-11-03_18-52-58](https://github.com/lico-n/ZygiskUnityCriwareKeylogger/assets/50344179/00aad4e9-9524-465a-909d-393fbc568e7c)
![Snipaste_2023-11-03_18-53-09](https://github.com/lico-n/ZygiskUnityCriwareKeylogger/assets/50344179/2fc839ba-d414-4618-9aeb-a306842b3150)

**Comment by ljgit428** [comment]
You are welcomed to try this app with your own setup. I still can’t get the key code.

APP Download Link: https://pkg.biligame.com/games/ylda_1.6.1_20230725_053258_fa4ed.apk

**Comment by lico-n** [comment]
Most games are implementing the Initialize with 4 params (key, authenticationFile, enableAtomDecryption, enableManaDecryption).

I have not encountered a game doing the Initialize with the CriwareDecrypterConfig which is why it is also not implemented yet. I would need a sample game to test it with.

This game is not calling the Initialize with CriwareDecrypterConfig either. I justed tested it.

The one with the 4 params is called once with a 0 key but that is probably for the usm's.
The one with the 1 config param is never called.

At least until the login screen where I stopped because I can't be bothered with real id verification. 
It is for example possible that initialization happens later, there are games that are doing per file keys etc which would mean they would initialize when the corresponding file is actually loaded.

You can try the module version below. It would log `Initialize (CriWareDecrypterConfig) called` if it detected such a call (without extracting the key for now). Unless confirmed that this is the case, I won't bother figuring out how to get through the bilibili login myself.

Also this module really only covers the generic encryption for Criware. If there is any custom encryption happening, then it won't be covered by this module.

[ZygiskUnityCriwareKeylogger-v1.0.0-zygisk-release.zip](https://github.com/lico-n/ZygiskUnityCriwareKeylogger/files/13257464/ZygiskUnityCriwareKeylogger-v1.0.0-zygisk-release.zip)

**Comment by ljgit428** [comment]
No problem. I have a real account with bilibili login, and I’ll try it out

**Comment by ljgit428** [comment]
The call has been detected: 
`Initialize (CriWareDecrypterConfig) called`
![Snipaste_2023-11-05_06-21-06](https://github.com/lico-n/ZygiskUnityCriwareKeylogger/assets/50344179/a53c7269-b28b-4905-85b9-731ecb31faa6)

**Comment by ljgit428** [comment]
@lico-n I also got the same 0 key while initializing CriwareDecrypter. The call `Initialize (CriWareDecrypterConfig)` is not detected, but I did not find a video .usm file in the app. I tried `.\hca.exe -c -a 00000000 -b 00000000 sample.hca` but that does not work for any of the hca files.

![Snipaste_2023-11-05_06-41-10](https://github.com/lico-n/ZygiskUnityCriwareKeylogger/assets/50344179/c36604f9-4d9f-4336-81df-4a649919a666)
![Snipaste_2023-11-05_06-42-54](https://github.com/lico-n/ZygiskUnityCriwareKeylogger/assets/50344179/b5645017-e1df-4865-a210-2abd8eb9d154)

**Comment by ljgit428** [comment]
@lico-n This is the screenshot where the decoder failed to decode the hca file:

`E:\collection\Azurlane\HCADecoder.v1.21>hca.exe -c -a 00000000 -b 00000000 E:\co
llection\BlueArchive\test\_vgmt_acb_ext_11000\awb\Main_11000_003.hca
E:\collection\BlueArchive\test\_vgmt_acb_ext_11000\awb\Main_11000_003.hca を復号
化中...

E:\collection\Azurlane\HCADecoder.v1.21>hca.exe E:\collection\BlueArchive\test\_
vgmt_acb_ext_11000\awb\Main_11000_003.hca
E:\collection\BlueArchive\test\_vgmt_acb_ext_11000\awb\Main_11000_003.hca をデコ
ード中...
Error: デコードに失敗しました。`

![Snipaste_2023-11-05_07-54-32](https://github.com/lico-n/ZygiskUnityCriwareKeylogger/assets/50344179/63dbf30e-d7c6-490e-a9b3-fd4a1dd983a4)

**Comment by lico-n** [comment]
Upload some samples for encrypted acb/awb?

**Comment by ljgit428** [comment]
@lico-n  Here is a complete version of acb/awb files:
https://drive.google.com/file/d/1uae1Hin__-hw1e0ibRfj3S3CD1z91e5Z/view?usp=sharing

**Comment by lico-n** [comment]
The reason why you don't see any Initialize calls is because these are not encrypted.

You are probably just using a tool that has not the proper support for the file format.

Try using
https://github.com/vgmstream/vgmstream
or if you like to do it programatically 
https://github.com/Youjose/PyCriCodecs

**Comment by ljgit428** [comment]
@lico-n Great! It is working using the Foobar2000 component from vgmstream(https://github.com/vgmstream/vgmstream)
Thanks a lot for help!

![Snipaste_2023-11-06_08-29-06](https://github.com/lico-n/ZygiskUnityCriwareKeylogger/assets/50344179/34e1a32e-59fd-4a77-813b-b5269d512ec4)
